### ISSUE TITLE
Find offline players

### ISSUE THREAD

**Issue by AttendantFox** [Minehut/Issues#101]
### Expected behavior
The network `/find` command is suppose to tell you how long an offline player has been offline.

### Actual behavior
When you do `/find <offline player>`, the system says `Player not found: <player>`

### Detailed steps to reproduce this behavior
Use the command `/find` with an offline player

**Comment by Trophonix** [comment]
Other commands behave similarly.

**Comment by lukechatton** [comment]
The API currently returns all the info needed to display when they were last online. Here is the response for finding a player that is offline. This should help you out @Trophonix 

```
{
  "not_found": false,
  "name": "Luuke",
  "last_online_date": 1497820431506
}
```

**Comment by MatrixTunnel** [comment]
Added :)
