### ISSUE TITLE
/force-motd doesn't support spaces

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#102]
### Expected behavior
/force-motd (name) Join my server!

### Actual behavior
[![https://gyazo.com/75300cedb33dc8ecc90f055d12a0b37b](https://gyazo.com/75300cedb33dc8ecc90f055d12a0b37b/raw)](https://gyazo.com/75300cedb33dc8ecc90f055d12a0b37b)

### Detailed steps to reproduce this behavior
do /force-motd (name) Any motd with spaces

### Server name
All servers

### Link to server logs
n/a

**Comment by tjhubz** [comment]
Matrix made a fix but it needs to be merged.

**Comment by Trophonix** [comment]
Fixed
