### ISSUE TITLE
Some server properties options not functioning properly.

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#103]
### Expected behavior
When clicking resource pack, world seed, or world border, it should prompt the user to enter a link/value.

### Actual behavior
Does not prompt user for anything.
[![https://gyazo.com/692ce2329125d14f7e2cc8175e600284](https://gyazo.com/692ce2329125d14f7e2cc8175e600284/raw)](https://gyazo.com/692ce2329125d14f7e2cc8175e600284)

### Detailed steps to reproduce this behavior
Do /minehut, click world properties, then click any of the last three options (world border, resource pack, or seed)

### Server name
SuperSpleef

### Link to server logs
"Unable to upload file," it says, sorry!

**Comment by Trophonix** [comment]
Working on it, thanks!

**Comment by Trophonix** [comment]
Fixed =)
