### ISSUE TITLE
Back button needed in world manager menu 

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#107]
### Expected behavior
Most menus have a back button to easily navigate minehut menu

### Actual behavior
Nothing is there
[![https://gyazo.com/50c935a50d52fd6b3c5c5af86d873148](https://gyazo.com/50c935a50d52fd6b3c5c5af86d873148/raw)](https://gyazo.com/50c935a50d52fd6b3c5c5af86d873148)

### Detailed steps to reproduce this behavior
/minehut > World Manager

### Server name
SuperSpleef

### Link to server logs
n/a

**Comment by MatrixTunnel** [comment]
Added :)
