### ISSUE TITLE
Multiple buttons do not give feedback in /minehut

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#109]
### Expected behavior
When clicking the "Buy a premium plan" or "reset OPs" button, it should give feedback (i.e. A confirmation message, or a link to the store, etc

### Actual behavior
Nothing is said, lonely
[![https://gyazo.com/f91b9dce0ff41209b186d6bef58a2d80](https://gyazo.com/f91b9dce0ff41209b186d6bef58a2d80/raw)](https://gyazo.com/f91b9dce0ff41209b186d6bef58a2d80)
[![https://gyazo.com/bdbf2177a9fd3708738f6c98410779c6](https://gyazo.com/bdbf2177a9fd3708738f6c98410779c6/raw)](https://gyazo.com/bdbf2177a9fd3708738f6c98410779c6)

### Detailed steps to reproduce this behavior
Click the "Buy a premium plan" or "reset OPs" buttons

### Server name
SuperSpleef

### Link to server logs
When doing /dl logs it doesn't tell me anything :/

**Comment by Trophonix** [comment]
The premium plan button works fine for me
![Gif](https://gyazo.com/10c564c351c5aa028035f5d69272fc41/raw)

I'll add feedback to Rest OPs.

**Comment by Trophonix** [comment]
Added.
