### ISSUE TITLE
Server list should only update when opened.

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#110]
When browsing the server list, it can sometimes be annoying how it updates every 2 seconds because you click a server just as it updates, and it sends you to a different server.
It should only update when the menu is opened, to prevent joining the wrong server.

**Comment by Trophonix** [comment]
The server list is a singular object which is updated every few seconds. There's not an efficient way to do this.

**Comment by drtshock** [comment]
We could have it update say every... 5 seconds instead? Otherwise, there isn't a great way to od it like Troph said.

**Comment by Trophonix** [comment]
I slowed down the updating.
