### ISSUE TITLE
Allow users to access the control panel

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#112]
There should be a way to give trusted users to the control panel. They can edit plugins, download the world, edit configs, etc. They should not be allowed to reset ops, only the owner should be able to do that. Commands could be as follows:

/cpaccess give <username> - gives access
/cpaccess remove <username> - removes access
/cpaccess list - lists people with access besides the owner
/cpaccess reset - removes all people from access list, besides owner

Only the owner should be able to use these commands, and should be blacklisted in both command blocks and create your own menus.

**Comment by tjhubz** [comment]
For users that don't have the best judgement, this would be a massive security problem. I don't think this feature will be added.

**Comment by happyzachariah** [comment]
While I can see why this would be a bad thing, for me this would be a great thing. My brother and I have a server but I can't edit. While you can have bad judgement, giving alot of people OP can be abused and is bad judgement. If people don't trust others, they just shouldn't do this.

What might would be nice is like when resetting, you bring up a prompt that is like a WARNING type thing that tells you the risks of this.

**Comment by iGalaxyYT** [comment]
Yeah, like a confirmation when you do the command, like a randomly generated code you have to type in chat
