### ISSUE TITLE
Deletion of worlds.

### ISSUE THREAD

**Issue by CommandFox** [Minehut/Issues#114]
When you upload a world, it cannot be deleted or removed in any way. Please add a command such as `/deleteworld` to allow this.

**Comment by tjhubz** [comment]
Resetting tge world doesnt work?

**Comment by MatrixTunnel** [comment]
That does work but he's talking about removing individual worlds after uploading them

**Comment by CommandFox** [comment]
Yeah

**Comment by tjhubz** [comment]
Aha

**Comment by Trophonix** [comment]
Added
