### ISSUE TITLE
Commands.yml

### ISSUE THREAD

**Issue by HaZePug** [Minehut/Issues#115]
### Expected behavior
Paste a link in and it changes commands.yml
### Actual behavior
It dose not change nothing it iver deletes the current one or dose nothing when you /rl

### Server name
Tazerprison

**Comment by tjhubz** [comment]
My commands.yml worked... What's the link to yours?

**Comment by HaZePug** [comment]
https://pastebin.com/raw/8fMQZRcf

**Comment by MatrixTunnel** [comment]
Try uploading it then doing `/stop` instead of reloading the server (I don't think reloads save)

**Comment by HaZePug** [comment]
Nope doesn't work all it comes up with is the link I pasted it dose not say what it use to say about restarting your server

**Comment by tjhubz** [comment]
Also, try doing a simpler commands.yml and see if it works, there could be an issue with your code.

**Comment by tjhubz** [comment]
Yeahit did that for me too but it still worked.

**Comment by HaZePug** [comment]
thx works must be a issue in my code

**Comment by CommandFox** [comment]
Move the `promotejrmod` command to the correct block indentation level.

**Comment by HaZePug** [comment]
>  Move the `promotejrmod` command to the correct block indentation level.

what dose block indentation level mean

**Comment by MatrixTunnel** [comment]
So it doesn't work if you have incorrect syntax? I'll add an error telling the user that the uploaded file won't work if they have invalid syntax if that's the case

**Comment by HaZePug** [comment]
thx that would help

**Comment by CommandFox** [comment]
Yes, it has the incorrect syntax. Also, block indentation level is basically the level that the line of text is on, in terms of the number of spaces before it.
