### ISSUE TITLE
/minehut does nothing ._.

### ISSUE THREAD

**Issue by FrostedWeFall** [Minehut/Issues#116]
### Link to server logs  : Whenever i try to do /dl log it says upload link failed >> http://prntscr.com/flb9bq <<

**Comment by tjhubz** [comment]
After a restart does it still do this?

**Comment by Bayside308** [comment]
Have you reloaded your server before it broke? As mentioned above, does the error persist upon restart?

**Comment by FrostedWeFall** [comment]
ive restarted multiple times and typed /rl multiple times and i still get no response! @Bayside308 @tjhubz

**Comment by lukechatton** [comment]
Reloading isn't supported.

**Comment by tjhubz** [comment]
Ok, so after a couple of days has it fixed itself?

**Comment by FrostedWeFall** [comment]
>> UPDATE << 
After about a week of it not working i decided to download my world, reset all in restart. It is not working without any problems? 
I feel as if it not working had something to do with me editing the config files so i recommend not to edit them lmao

You can close or delete  this if you want , i have no further comments. Thanks for all your all support and help :D
