### ISSUE TITLE
Can't join server.

### ISSUE THREAD

**Issue by CryptedData** [Minehut/Issues#118]
Expected Behavior

When you do **/join** (eg. MiniatureGames), it supposed to take you to that server after start up.

Actual behavior

When trying to join your server, it keeps telling you "Starting server, please wait" then it says "Your requested server was unresponsive on startup. Please try again."

Detailed steps to reproduce this behavior

When trying to join your server, it actually takes you to your server.

Server name

MiniatureGames

**Comment by MatrixTunnel** [comment]
This might be related to issue #120

**Comment by CryptedData** [comment]
Okay tanku

**Comment by lukechatton** [comment]
Fixed!
