### ISSUE TITLE
Startup not working on some servers.

### ISSUE THREAD

**Issue by scorpion808** [Minehut/Issues#121]
### Expected behavior
/join a server and let it start up.

### Actual behavior
And shows this [printscr](http://prntscr.com/flt7nn) as it is starting up.

### Detailed steps to reproduce this behavior
/join a server that is already not online and does that ^.

### Server name
PvpInTheSky
### Link to server logs
Cannot get.

**Comment by lukechatton** [comment]
I manually fixed your server. This issue will no longer persist after tonight's restart.
