### ISSUE TITLE
Can't install tier plugins even though I have the required tier

### ISSUE THREAD

**Issue by Snixtrix** [Minehut/Issues#122]
### Expected behavior 
Should be able to get Tier 3 plugins

### Actual behavior 
I only get the plugin slots and player slots, not the tier 3 plugins

### Detailed steps to reproduce this behavior 
1. Have tier 3
2. Try to install Tier 3 plugins

### Server name 
Mobz

**Comment by HaZePug** [comment]
I'm having the same issue when will a fix be realeased

**Comment by Snixtrix** [comment]
I changed the name to Breeze

**Comment by Trophonix** [comment]
I've pushed an attempted fix for this issue. Will close once it's confirmed to be fixed.

**Comment by MatrixTunnel** [comment]
Confirmed fixed :)

**Comment by MatrixTunnel** [comment]
Appears this hasn't been fixed even though it's working for me. Server` 58ba9275d56bb4089d2e972e` is having the issue

**Comment by MatrixTunnel** [comment]
It appears that setting the server's tier fixed the issue.
