### ISSUE TITLE
Tier 4 

### ISSUE THREAD

**Issue by ConstillationsTier4** [Minehut/Issues#124]
So, first my server was not working, it would not start so i went to teejers and he helped fix it. 

But there was one problem. I could get my 26 plugins because i already had tier 4, but not the plugins which require the tier!

### Detailed steps to reproduce this behavior
1. Have tier 4
2. Try to install a plugin which requires tiers

### Server name 
SkyCube

**Comment by Trophonix** [comment]
Duplicate: #122
