### ISSUE TITLE
Suggested Commands

### ISSUE THREAD

**Issue by NovaLaser** [Minehut/Issues#125]
Since the Minehut update, a lot of things have been broken and/or removed. Example: plugins and previous features. I think Minehut should add server histories and searches. If Minehut can't do this next one, I'm fine, but hopefully, Minehut could go back to 1.11.2 or something to add all of its original plugins it had.

**Comment by tjhubz** [comment]
To reverse the work we have already done would be detrimental. All of the features, except maybe the plugins, you talked about will be added back eventually.

**Comment by Trophonix** [comment]
To clarify, none of the changes you mentioned had anything to do with 1.12. We did a full re-code of the network and some features haven't been ported over yet. Reverting to the old plugins would basically mean re-introducing a ton of bugs.
