### ISSUE TITLE
Kick upon Death

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#126]
**Expected Behavior**

You die and respawn in the server you are currently on.

**Actual behavior**

Kicks you out of server upon death.

**Detailed steps to reproduce this behavior**

When you die, you actually respawn in the server.

**Server name**

MiniatureGames (580c0f4606979b1a49719d72)

**Server Logs**

N/A

**Comment by tjhubz** [comment]
Server logs are needed.

**Comment by Criticalz** [comment]
How to get them ._. I feel dumb.

**Comment by 0rbity** [comment]
@Criticalz You can get them using /dl log.

_Sent from my Samsung SM-J510FN using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Trophonix** [comment]
Run /dl log on your server.

**Comment by Criticalz** [comment]
Close this please. Issue is resolved

**Comment by tjhubz** [comment]
You can vlose the issue yourself, no need for an admin
