### ISSUE TITLE
Essentials Commands Not Working.

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#127]
**Expected Behavior**

You can use essentials commands (/help etc...)

**Actual behavior**

Every time you do /spawn or /help etc... it says "Error: null"

**Detailed steps to reproduce this behavior**

When you type (e.g. /spawn) you actually get teleported to the server spawn.

**Server name**

MiniatureGames (580c0f4606979b1a49719d72)

**Server Logs**

N/A

**Comment by HaZePug** [comment]
Same thing here idk how to fix it

**Comment by MatrixTunnel** [comment]
Please provide server logs by doing `/dl log` on your server after doing some essentials commands

**Comment by MatrixTunnel** [comment]
After looking at your logs, I think GroupManager is the cause of the problem. I recommend switching to pex due to GM being broken in 1.12
