### ISSUE TITLE
Fix /discord and /website (/forums) formatting

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#128]
### Expected behavior
when doing /discord, /website and /forums, the formatting should match the rest of the network.

### Actual behavior
[![https://gyazo.com/056a47ef2dc2029710b56a0d134e4991](https://gyazo.com/056a47ef2dc2029710b56a0d134e4991/raw)](https://gyazo.com/056a47ef2dc2029710b56a0d134e4991)
ew

### Detailed steps to reproduce this behavior
do /discord, /website, or /forums

### Server name
:I 

### Link to server logs (/dl log)
:I

**Comment by Trophonix** [comment]
Done.
