### ISSUE TITLE
Unmute only works after relog

### ISSUE THREAD

**Issue by Disastur** [Minehut/Issues#129]
### Expected behavior
players unmuted can talk the instant they are unmuted.

### Actual behavior
Players unmuted need to relog first.

### Detailed steps to reproduce this behavior
/mute {NAME} test 5m
/unmute {NAME}
let {NAME} type a message in chat

**Comment by Trophonix** [comment]
I'm working on this.

**Comment by MatrixTunnel** [comment]
Fixed :)
