### ISSUE TITLE
Essentials Chat Issue <> 

### ISSUE THREAD

**Issue by HaZePug** [Minehut/Issues#130]
### Expected behavior
It should show prefixes and suffixes in chat

### Actual behavior
It says this <HaZe_Pug> And also they are **No** Prefixes allowed iver

### Detailed steps to reproduce this behavior
Set a prefix and/or suffix and then try to chat

### Server name
tazerprison

### Link to server logs (/dl log)
Don't Think You need this but if you do I will put it here

**Comment by Trophonix** [comment]
Yes, a link to server logs would be helpful. That's why we put it there. ;) @HaZePug

**Comment by MatrixTunnel** [comment]
My guess is that GroupManager is causing problem. Please uninstall it/use a different plugin and report back here :)
