### ISSUE TITLE
Cannot join my server (Mines)

### ISSUE THREAD

**Issue by Scribea** [Minehut/Issues#133]
### Expected behavior
When doing /join Mines, it would join the server.

### Actual behavior
When doing /join Mines, it keeps telling you "Starting server, please wait" then it says "Your requested server was unresponsive on startup. Please try again." 

### Detailed steps to reproduce this behavior
When joining server, it would actually send to the server.

### Server name
Mines

### Link to server logs (/dl log)
--
---

PS: This might be related to issue #120

**Comment by Criticalz** [comment]
Coreprotect broke servers. Contact any admin.

**Comment by Scribea** [comment]
Already did, no response.

**Comment by MatrixTunnel** [comment]
@Criticalz Turns out it wasn't CoreProtect. It was Docker being weird
