### ISSUE TITLE
FT13 Plugin Bug

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#134]
### Expected behavior
Supposed to respawn at the spawn of server when die.

### Actual behavior
When you die, even if it isn't in the minigame, you should be able to respawn at the server spawn.

### Detailed steps to reproduce this behavior
Edit config files. The official config files, not in game.

### Server name
MiniatureGames 

### Link to server logs (/dl log)
On ipad. Soz. I'll edit later

**Comment by tjhubz** [comment]
This isn't a bug, it's a feature you want to be added.

**Comment by MatrixTunnel** [comment]
This appears to be an issue with the plugin because it hasn't been updated to 1.12. Please contact the plugin author to resolve this issue as we are not responsible plugin updates
