### ISSUE TITLE
The register system to forum didn't work

### ISSUE THREAD

**Issue by TheNiceBurger** [Minehut/Issues#139]
### Expected behavior
When i use /login on lobby server send a mesage saying "Unknown command. Type "/help" for help."

### Actual behavior
Makes impossible register the forum acount

### Detailed steps to reproduce this behavior
only use /login or /reset-password on server lobby

### Server name
The server lobby

### Link to server logs (/dl log)
null

**Comment by lukechatton** [comment]
I tested the command on all servers. Make sure you type the right command. You also have to do this in /lobby
