### ISSUE TITLE
Uploading Worlds Not Working

### ISSUE THREAD

**Issue by NubletSoup** [Minehut/Issues#140]
So I recently uploaded a map known as "Broville" to my server, but all it does is just turn the world all water. I tried resetting the world several times and tested the map if it worked on single player and it did. 

This is my map I'm trying to install
https://www.dropbox.com/s/uu2wx2m6jppx8k0/Final%20C%20Broville%201.11.zip?dl=0
Change 0 to 1 at end of link for link to upload

I've been trying to get it to work for the past 8 hours and grew very frustrated leading me to ask for help now on minehut forums. 

Please help thanks!

Server name : Escraft

**Comment by tjhubz** [comment]
You provided no information. There is no way we can help you.

**Comment by Trophonix** [comment]
When you upload a world and teleport to it, it teleports you to the vanilla "world spawn". The map maker may have not changed that. Try teleporting around, like go to /tp 0 100 0.

**Comment by NubletSoup** [comment]
I have tested this on my single player and it shows the exact cords as on the moment server. I have tried tp'ing to the cords you sent me and nothing is there. 

I have reset world over ten times.
I have save-all when uploading a server before restarting.
I have re uploaded world over ten times. 
If maybe a developer could take a look at my map and see what's wrong that would be great. None of the other staff or players know what's wrong.

**Comment by Trophonix** [comment]
I'm sorry, but I honestly cannot see how this could possibly be an issue on our end. I've tested the world uploading extensively, and it works totally fine. This is almost certainly an issue with the world, your download of the world, or the site you downloaded it from. I don't really know what I can do or say.

**Comment by NubletSoup** [comment]
Do you have a skype that I can contact you... I tried over 20 times testing this map, works fine on single but when it comes to minehut server it doesnt work

**Comment by NubletSoup** [comment]
The map file is 236 MB, can you maybe try uploading my map on a test server

**Comment by NubletSoup** [comment]
So update, I've managed to upload the map to my server, but instead of spawning me in the location where you're suppose to spawn on map it telelports me to the end of the map. If someone could assist me in this that would be  great. Here's new map link 👍 https://www.dropbox.com/s/i87i8qrggnhuxxl/6.23.2017.zip?dl=1

**Comment by Trophonix** [comment]
I did `/ul world test https://www.dropbox.com/s/i87i8qrggnhuxxl/6.23.2017.zip?dl=1`
then `/world test`
and I spawned exactly where you're meant to spawn. o_O
