### ISSUE TITLE
[SERVER] My server isn't starting.

### ISSUE THREAD

**Issue by CoverMC** [Minehut/Issues#141]
### Expected behavior
Server isn't starting.

### Actual behavior
When ever I start my server, it'll say "Starting server... Please wait." 

### Detailed steps to reproduce this behavior
If you can fix my server that'll be great because I need to make a server. 

### Server name
Cells

### Link to server logs (/dl log)
I couldn't do **/dl log** because my server is broken.

**Comment by lukechatton** [comment]
Fixed. Just make sure to run /reset-all next time you start it up.
