### ISSUE TITLE
My Server Is Not Starting Up

### ISSUE THREAD

**Issue by 21Vap3** [Minehut/Issues#144]
### Expected behavior
Server isn't starting.

### Actual behavior
When ever I start my server, it'll say "Starting server... Please wait.
### Detailed steps to reproduce this behavior
If you can fix my server that'll be great because I need to make a server.

### Server name
CubezCraft

### Link to server logs (/dl log)
I can't get on my server.

**Comment by Trophonix** [comment]
Handled. :)

Related: #120
