### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by jorgeberrex** [Minehut/Issues#146]
### Expected behavior
Translate server messages to the player's client language. 

### Actual behavior
- Displays translation message key. 
- For the messages that do work, can't display some characters properly, such as `á é í ó ú ü ñ`.

[http://imgur.com/rUBSlAc](http://imgur.com/rUBSlAc)

### Detailed steps to reproduce this behavior
Set client language to a supported language, in my case Spanish, and install a plugin or use `/rl`

### Server name
Voxel

### Link to server logs (/dl log)
No errors shown in the log, and I will not be linking it as it contains player IPs.

**Comment by MatrixTunnel** [comment]
Thank you for updating it @jorgeberrex :)
