### ISSUE TITLE
/reload "Bypassable"

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#152]
### Expected behavior
/rl (/reload) will not do anything even if you do /execute @p ~ ~ ~ rl.

### Actual behavior
You would be sent a warning message and reason of why it is disabled when doing /rl or doing /execute @p ~ ~ ~ rl

### Detailed steps to reproduce this behavior
Make it an illegal command or just... idk. Just don't make players do that command. xd

### Server name
MiniatureGames
### Link to server logs (/dl log)
https://transfer.sh/13Bdjy/latest.log

**Comment by Criticalz** [comment]
Umm... bump?

**Comment by Trophonix** [comment]
Oh, forgot to close this. It's fixed now. =)

**Comment by Criticalz** [comment]
Umm, it isn't fix

**Comment by Trophonix** [comment]
Aha, I fixed it now.
