### ISSUE TITLE
Update UltraCosmetics plugin.

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#153]
### Expected behavior
UltraCosmetics plugin will work when installed and is compatible on the latest version of MC (1.12)

### Actual behavior
UltraCosmetics plugin will not work when installed and is only compatible on MC version 1.11

### Detailed steps to reproduce this behavior
Update Plugin (Go to  https://www.spigotmc.org/resources/ultra-cosmetics-opensource-and-free-1-8-1-12.10905/)

### Server name
MiniatureGames

### Link to server logs (/dl log)
https://transfer.sh/15VdIy/latest.log

**Comment by MatrixTunnel** [comment]
Updated! Please reply if it works or not :)

**Comment by Criticalz** [comment]
Thanks! It works.
