### ISSUE TITLE
Server unresponsive on startup

### ISSUE THREAD

**Issue by FactoDoesStuff** [Minehut/Issues#154]
### Expected behavior
The server is supposed to start up normally.

### Actual behavior
Server proclaims itself as unresponsive at startup. 

As seen here: [Click!](http://i.imgur.com/yqTWrW2.png)

### Detailed steps to reproduce this behavior
Joining specified server below will cause this error. 

### Server name
-Clickerz-

### Link to server logs (/dl log)
Cannot get server logs as /dl log doesn't work from the lobby.

**Comment by Criticalz** [comment]
Do you have coreprotect? Or had?

**Comment by MatrixTunnel** [comment]
@Criticalz Turns out CoreProtect wasn't the problem.

When was the las time you were able to start your server Facto?

**Comment by Criticalz** [comment]
But there was a file called "core", wasn't there? Lucas made a post about it though.

**Comment by MatrixTunnel** [comment]
That file actually wasn't generated by CoreProtect. It was from issue #120

**Comment by FactoDoesStuff** [comment]
I haven't attempted to start my server since when the startup issue was making my server crash upon joining. So, the last time I was able to start up my server, or at least attempted to and was successful, was about 22 days ago. @MatrixTunnel

**Comment by MatrixTunnel** [comment]
Make a comment on issue #120 with your server name since that appears to be the problem
