### ISSUE TITLE
Minehut redirect error

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Minehut/Issues#158]
### Expected behavior
On the bottom of the website in the sitemap area when you try clicking "Shop," it's supposed to take you to the Minehut store.

### Actual behavior
Instead, it attempts to take you to "https://minehut.com/shop" instead of "https://store.minehut.com" which then gives a 404 error.

![minehutsitemap](https://user-images.githubusercontent.com/16548272/27559546-e84c89ce-5a8e-11e7-8bca-f3410659bba6.png)

### EDIT:
The same is when you try clicking the "Twitter" button at the bottom of the page, it's mispelled as "ttps" instead of "https"

[![https://gyazo.com/589c5fae6d3d8ba12a69bc05111cf769](https://gyazo.com/589c5fae6d3d8ba12a69bc05111cf769/raw)](https://gyazo.com/589c5fae6d3d8ba12a69bc05111cf769)

**Comment by Criticalz** [comment]
I don't seem to have this issue.

**Comment by Sprule** [comment]
Fixed. thanks for catching this
