### ISSUE TITLE
Server wont start just says start server please wait...

### ISSUE THREAD

**Issue by Rambut** [Minehut/Issues#159]
### Expected behavior
[To start the server and people can play]

### Actual behavior
[Just wont start up]

### Detailed steps to reproduce this behavior
[To look into the files and see if there's a error]

### Server name
[GalaxyCenter]

**Comment by HaZePug** [comment]
Post your server name and say mine won't start up at #120 if it dose t work as a link scroll down to "docker Brocken servers"

**Comment by Rambut** [comment]
Wow I did what you said and it put it in the same spot

**Comment by Trophonix** [comment]
Fixed. =)
