### ISSUE TITLE
Online Mode

### ISSUE THREAD

**Issue by Zqnn** [Minehut/Issues#16]
**The issue**

Regarding 3rd party servers, when all steps [[Steps]](https://minehut.com/thirdparty) have been completed, the error message 

> Unable to start! Server is online mode!

Is displayed.

**Miscellaneous information**
Screenshot of error message - 
[Error Message](https://gyazo.com/caf56bc2b24ee4fde810f3d8748ee57b)

**Sorry if this issue has been addressed, I tried to find a solution but was unable to.**

**Comment by lukechatton** [comment]
Removing all Third Party Server related Issues.
