### ISSUE TITLE
You could add a custom scoreboard plugin

### ISSUE THREAD

**Issue by HaZePug** [Minehut/Issues#160]
It would be cool if you could add a custom scoreboard plugin for us as I tried doing a custom one **failed**

**Comment by HaZePug** [comment]
Sorry about the issue spam I clicked send issue by accident  so I had to edit it

**Comment by Criticalz** [comment]
That would be a cool plugin! I only found one yet this looks cool but has way more stuff than needed: https://www.spigotmc.org/resources/ctsnc-★-animated-scoreboard-and-tablist-nametag-chat-★-protocol-hack-1-8-1-11.10714/

**Comment by HaZePug** [comment]
Yeah I like that one too but I think you would need two plugins for that but you could do the core plugin free and the reset takes a plugin slot

**Comment by tjhubz** [comment]
You can make a pull request in the plugins repo of the minehut github

**Comment by Criticalz** [comment]
The CTSNC plugin only needs placeholderAPI which they removed. But it got updated.

**Comment by tjhubz** [comment]
#171
