### ISSUE TITLE
Server Won't start up says starting server please wait...

### ISSUE THREAD

**Issue by Rambut** [Minehut/Issues#161]
Expected behavior

[To start the server and people can play]

Actual behavior

[Just wont start up]

Detailed steps to reproduce this behavior

[To look into the files and see if there's a error]

Server name

[GalaxyCenter]

**Comment by HaZePug** [comment]
Don't double post

**Comment by Rambut** [comment]
I did what you said

**Comment by Trophonix** [comment]
Fixed.
