### ISSUE TITLE
Unresponsive Tier 4

### ISSUE THREAD

**Issue by ConstillationsTier4** [Minehut/Issues#163]
### Expected behavior Hello, I have had the tier 4 for a long time but when luuke fixed the servers it stopped working. I can get 26 plugins but not any tier plugins.
[answer]

### Actual behavior
[answer]I can only get default plugins but i can get 26 default plugins, no tier plugins.

### Detailed steps to reproduce this behavior
?
[answer]

### Server name
[answer]SkyCube

### Link to server logs (/dl log)
[answer]
?

**Comment by Trophonix** [comment]
Duplicate: #122
