### ISSUE TITLE
Worldedit command: /gmask , /mask

### ISSUE THREAD

**Issue by YouTubeJr** [Minehut/Issues#164]
### Expected behavior
when i type /gmask air , it pop up a error message

### Actual behavior
when i type /gmask air it should replace only air blocks!

### Detailed steps to reproduce this behavior
/gmask and /mask

### Server name
(insane) but happends on all servers i try this command on!

### Link to server logs (/dl log)
https://www.mediafire.com/?33sxjfctxt3d5lm

**Comment by tjhubz** [comment]
This is a bug related to the plugin, not minehut itself. Please notify the plugin creator of this issue instead of us.
