### ISSUE TITLE
[small] unmute display error

### ISSUE THREAD

**Issue by Disastur** [Minehut/Issues#165]
### Expected behavior
says the staff has unmuted the player.

### Actual behavior
says the player has unmuted themselves.

### Detailed steps to reproduce this behavior
unmute a player

### Link to server logs (/dl log)
![image](https://user-images.githubusercontent.com/29286256/27748198-c6429a2e-5dce-11e7-92eb-7ced6ccf3b58.png)

**Comment by Trophonix** [comment]
Fixed!
