### ISSUE TITLE
Tier 1 Issue

### ISSUE THREAD

**Issue by MysticPiggy** [Minehut/Issues#167]
### Expected behavior
I have Tier 1 and I'm trying to install Citizens and CommandNPC on my server
### Actual behavior
It is saying that I need to buy Tier 1 even though i have already bought it and payed for it this month.
### Detailed steps to reproduce this behavior
I have no clue, it just won't install the plugins

### Server name
MysticRPG

### Link to server logs (/dl log)
https://transfer.sh/UZUcK/latest.log

**Comment by Trophonix** [comment]
Duplicate: #122
