### ISSUE TITLE
Title welcome message tabs not working

### ISSUE THREAD

**Issue by FrostedWeFall** [Minehut/Issues#172]
### Expected behavior
To change the tab to the text i typed
### Actual behavior
Says it changed but has not visually, ive tried restarting , does nothing

### Detailed steps to reproduce this behavior
Im not completly sure to be honest
PROOF: http://prntscr.com/fqigww

### Server name
TNTSpleef
### LINK TO SERVER LOGS
"Upload Failed"

**Comment by Criticalz** [comment]
The plugin hasn't updated yet.

**Comment by FrostedWeFall** [comment]
ahh okay , thank you for that

**Comment by FrostedWeFall** [comment]
Closing Issue!
