### ISSUE TITLE
Reload "Bypassable" Again

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#176]
### Expected behavior
/rl would not be bypassable even by an item with a command from CreateYourOwnMenus plugin.

### Actual behavior
/rl Bypassable with the Createyouownrmenus plugin. How? Just hold an item and do /menu script add /rl
### Detailed steps to reproduce this behavior
Make it an illegal command for a while or disable it from CreateYourOwnMenus plugin.

### Server name
MiniatureGames

### Link to server logs (/dl log)
https://transfer.sh/aHEeJ/latest.log ALSO remember that /dl log sometimes doesn't work. An issue was made down below.

**Comment by Trophonix** [comment]
Ugh. -_-

Honestly, it's not a big deal if there are some small obscure bypasses to it. The command was disabled for the good of the players. If they use it, they're just ensuring that they won't be able to get any help with bad things that happen because of it. 

I will try to fix this though.

**Comment by Criticalz** [comment]
Alright. You seem annoyed for some reason. I won't post another one xd.
