### ISSUE TITLE
Minehut translated

### ISSUE THREAD

**Issue by Tsun-Shun** [Minehut/Issues#182]
I know that a lot of people in the lobby don't speak fluent English or don't speak it that well, so maybe a way to have everything translated to the language the user chooses. You can get everything translated by having a team with people that know a language fluent and let them translate everything for the players. This will help a lot of players that don't speak English or don't know a lot of it.

**Comment by lukechatton** [comment]
We have a full translation framework in place. Currently the only supporting languages are English and Spanish. We hope to add more languages in the near future.
