### ISSUE TITLE
Tier 1 not actually cheaper (as stated in forums post)

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#192]
### Expected behavior
Tier 1 should be cheaper.

### Actual behavior
Tier 1 is still $5.

### Detailed steps to reproduce this behavior
Go to the minehut store and look at the price.
(I was using Stripe payments to view it)

**Comment by drtshock** [comment]
The announcement says that it will be getting cheaper with the tier updates later today.
