### ISSUE TITLE
Minehut  is not recognizing that I'm Tier 3 [Lifetime] 

### ISSUE THREAD

**Issue by Czechiia** [Minehut/Issues#193]
**EDIT**

This is no longer cannon, please Close this post. Thanks for the fix ^^

### Expected behavior

- Larger World Border
- 45 Player Slots*
- Access to exclusive donor plugins. (Even though Snixtrix's issue seems to be solved, mine is not.)

### Actual behavior

Minehut recognizes my server as a non-tiered server.

### Detailed steps to reproduce this behavior

- Have an Lifetime Tier 3 Server.
- Try getting the following listed above.

### Server name
Mythos

### Link to server logs (/dl log)
[https://transfer.sh/LK3Cf/latest.log](https://transfer.sh/LK3Cf/latest.log)

### *

While it seems that I have 45 Player Slots on Minehut, it says I have 10 on Essentials.

**Comment by HazryG** [comment]
This is also happening to me as I can't use any tiered plugins and I have permanent Tier 3. I believe that my plugin slots/player slots are still the same, however.

**Comment by iGalaxyYT** [comment]
You can get lifetime server plans?

**Comment by Czechiia** [comment]
@iGalaxyYT Not anymore, I got this lifetime plan back in Feb 2016 when it was part of the "PRO" package. Minehut no longer offers this.

**Comment by tjhubz** [comment]
Is it working now @Czechiia?

**Comment by Czechiia** [comment]
The issue was fixed so yes @tjhubz

**Comment by tjhubz** [comment]
You can close the issue then please :)
