### ISSUE TITLE
Lobby 2 bug

### ISSUE THREAD

**Issue by Tsun-Shun** [Minehut/Issues#197]
### Expected behavior
Can do /ely
Doesn't see when people join the lobby
Can fly
Has a compass and book in their inventory
Has a rank infront of their name if they have it

### Actual behavior
Can't do /ely (with a rank)
Sees the default "[user] joined the game" message
Can't fly
Doesn't have anything in their inventory
Doesn't have a rank 

### Detailed steps to reproduce this behavior
Go to lobby 2 and try to do these things

### Server name
lobby 2

### Link to server logs (/dl log)
Can't do this since it's not my server

**Comment by tjhubz** [comment]
Fixed by a restart.
