### ISSUE TITLE
Minehut sees my server as None-Tier [LifeTimeTier]

### ISSUE THREAD

**Issue by xKoalaHD** [Minehut/Issues#198]
Expected behavior

Access to the Skript Manager
Exclusive Plugins:
Scaffold (Import Worlds)
Multiverse-Core
Towny
Towny Chat
25 Max Plugins
60 Max Players
All content from tiers 1-3

Minehut recognizes my server as a non-tiered server.

Detailed steps to reproduce this behavior

Have an Lifetime Tier 4 Server.
Try getting the following listed above.
Server name

Glide

Link to server logs (/dl log)
https://transfer.sh/HVyFz/latest.log

**Comment by tjhubz** [comment]
Your purchase history has been checked, and you have charged back all of your purchases from minehut.
