### ISSUE TITLE
Lifetime Tier not recognized.(recurring problem throughout Minehut)

### ISSUE THREAD

**Issue by PsionKing** [Minehut/Issues#199]
Hello! Currently permanent tiers were reimplemented onto Minehut. I believe I should've received this as I had a bugged permanent tier. If I am mistaken, please forgive me.

**EXPECTED BEHAVIOUR**

Exclusive Plugins:
14 Max Plugins
32 Max Players
2GB Ram

**ACTUAL BEHAVIOUR**

Minehut recognizes my server as a non-tiered server.

**DETAILED STEPS TO REPRODUCE BEHAVIOUR**
Getting a Lifetime Tier 2.

**SERVER NAME**

Pathfinder

**Comment by tjhubz** [comment]
You never purchased a tier when they were permanent.
You did, however, purchase a monthly tier, so maybe you are confused as to which is which.

**Comment by PsionKing** [comment]
tjhubz, I had a bugged permanent tier which Teejers said I would get.
