### ISSUE TITLE
Haven't received my perm Tier.

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Minehut/Issues#202]
### Expected behavior
When I start my server, I'm supposed to have one of the old perm tiers.

### Actual behavior
My server only has the free plan, and never received the perm tier 2 back for months now.

### Detailed steps to reproduce this behavior
Seems like after I had tier 4 for 2 months and stopped paying for it I lost access to the perm tier and never got it back since

**Comment by tjhubz** [comment]
Confirmed payment, tier 2
