### ISSUE TITLE
Website Login Issue

### ISSUE THREAD

**Issue by Kronchical** [Minehut/Issues#203]
I am not able to login to minehut on PC right now so I use Minechat so I recently changed my name so when I go on to get my new password with /reset-password I can't click on it because I am on Minechat

**Comment by tjhubz** [comment]
That isn't of our concern. For the majority of players, they do not need to use their phone to log in.

**Comment by Kronchical** [comment]
your stupid :/

**Comment by Draem** [comment]
And you aren't

**Comment by Draem** [comment]
You're*

**Comment by MatrixTunnel** [comment]
I'm pretty sure the reason causing this is related to issue #97

**Comment by Draem** [comment]
So calm about someone just insulting teajars
