### ISSUE TITLE
Server goes down after a while.

### ISSUE THREAD

**Issue by pixelJavascript** [Minehut/Issues#205]
### Expected behavior
Your server should stay up as long as someone is playing on it.

### Actual behavior
The server will start but after a while it will go down throwing me an error
![error](https://user-images.githubusercontent.com/29942916/27901791-1a8eff24-61cf-11e7-9f48-73d4a542449e.png)
then returns me to the lobby.

### Server name
Anthem

### Link to server logs (/dl log)
It says it could not retrieve metadata.

**Comment by tjhubz** [comment]
Make sure you aren't in /vanish

**Comment by pixelJavascript** [comment]
Ohhhhhh damn I was

**Comment by pixelJavascript** [comment]
I'll see if that fixes it

**Comment by tjhubz** [comment]
It puts you in vanish every time you join due to an essentials config, keep that in mind. You can change "allow-silent-join-quit" to deny to stop it in the essentials config editor. (Then /save-all and /stop)
