### ISSUE TITLE
Worldborder restriction not removed!

### ISSUE THREAD

**Issue by PsionKing** [Minehut/Issues#208]
**EXPECTED**

When I start my server, the world's borders should be removed

**ACTUAL BEHAVIOR**

The world border stays where it was since before the update.

**STEPS TO REPRODUCE BEHAVIOUR**

Perhaps an administrator could remove the world border or something. I'm not entirely sure(sorry for the vagueness).

**Comment by tjhubz** [comment]
This should be fixed now.
