### ISSUE TITLE
[DTW] Lake View & Hackers (Miscellaneous)

### ISSUE THREAD

**Issue by TheBestGameeer** [Minehut/Issues#21]
**1. LAKE VIEW:**
 The map Lake View presents an overpowered bow on top of the mountain hidden from normal sight. Players that know about this bow continuously rush for it and start bowspamming the other team until they are killed or the match ends. It was [reported in this post](https://minehut.com/forums/topics/578d6a1c54b198904f1b8401) but no staff replied to it nor took interest in removing said bow.

**2. Major increase of hackers in Warzone & a suggested ability for Staff members.**
AAC was added but later removed because of the issues it had. Now the amount of hackers in Valor has been highly increased. Is AAC still worked on to be stable?
Talking about the staff perk, this has already been suggested twice in this GitHub, which describes how staff members should be able to join Warzone silently to avoid hackers to toggle. I give this idea a +1

EDIT: Warlock issue removed because map is currently removed due to original authors asking for removal.

**Comment by Palmidence** [comment]
Make a separate issue for each concern.

**Comment by MatrixTunnel** [comment]
AAC works and was completely stable. It doesn't work well with DTW because of how the kits work. I'm sure with a bit of reconfiguration, the plugin would work perfectly well
