### ISSUE TITLE
Slimefun PLUGIN [ERROR]

### ISSUE THREAD

**Issue by qinqy** [Minehut/Issues#211]
### Expected behavior
To actually work...
### Actual behavior
Showing red in /plugins and not working AT ALL

### Detailed steps to reproduce this behavior
Uh... I don't know... 

### Server name
Grassy

### Link to server logs (/dl log)
https://hastebin.com/nuqohapedu

**Comment by tjhubz** [comment]
@MatrixTunnel

**Comment by MatrixTunnel** [comment]
Fixed :)
