### ISSUE TITLE
Max players issue

### ISSUE THREAD

**Issue by Tsun-Shun** [Minehut/Issues#214]
### Expected behavior
Says 4/4 players when it's full

### Actual behavior
Says 4/10 players when it's full

### Detailed steps to reproduce this behavior
Go in the lobby, click the compass and look at a free server that has 4 players in it.

### Server name
Can be any free server that's full

### Link to server logs (/dl log)
Can't send this because it's a bug for multiple servers

**Comment by MatrixTunnel** [comment]
Fixed :)
