### ISSUE TITLE
Cant join server after setting afk limit to 10000000000000

### ISSUE THREAD

**Issue by Marble870** [Minehut/Issues#216]
### Expected behavior
Able to join server and have afk limit of 1000000000000000000

### Actual behavior
Kicks me instantly as soon as I join the server because I have been 'idle for too long'.

### Detailed steps to reproduce this behavior
Well, set the afk limit to an extreme number such as 10000000000000. 

### Server name
OldSchoolVanilla

### Link to server logs (/dl log)
Could not get logs because i was not able to join my server :/

### IMPORTANT extra note.
If you are able to fix this, please DO NOT do a /reset all. my friends, brother and I worked so hard on the world and would not be able to see it all reset! Anyways, thanks for the help, keep up the good work and glhf! :)

**Comment by HaZePug** [comment]
I had this problem and I could not get it working after so the only way I could fix it is by /reset-all because resetting the world did not work

**Comment by tjhubz** [comment]
You must /reset-all, there is no way to fix this externally.
