### ISSUE TITLE
Bought Tier 4 and havent got it

### ISSUE THREAD

**Issue by Bennzzzey** [Minehut/Issues#217]
### My Minehut Problems
I bought the Tier 4 on minehut, but I haven't got it yet!
I've asked staff to help me about it, and they do help me, but it still didn't work.
All I ask for is someone who can fix it can help me!

### Server Name
Bennzzzey

### My username
Bennzzzey

**Comment by tjhubz** [comment]
Confirmed payment, last payment was on the 7th of July.

**Comment by Bennzzzey** [comment]
Yea, I bought 7th of July. Bit I haven't got the Tier yet, help?

**Comment by tjhubz** [comment]
Still having the issue @Bennzzzey?
