### ISSUE TITLE
My diamond tier perm is not working

### ISSUE THREAD

**Issue by JawsGamezHD** [Minehut/Issues#219]
### Expected behavior
[answer]
It's supposed to be unlimted plugins BUT, the problem is, it's not working
### Actual behavior
[answer]
It says "go to the store to buy the tier"
### Detailed steps to reproduce this behavior
[answer]
Well when I bought it, it says "GO to the store to buy the rank. Store.minehut.com" idk why even those I bought the tier.
### Server name
[answer]
Murderr
### Link to server logs (/dl log)
[answer]
https://hastebin.com/duqitavoya

**Comment by Criticalz** [comment]
Contact an administrator (I prefer discord) and show them proof of your purchase. You should be sent a receipt in your email with the transaction code or ID. If you didn't receive an email, it most likely didn't go through and no money was lost. If you got PayPal it is an easier way of getting the I'd.

**Comment by tjhubz** [comment]
Actually, there is no need to contact an admin, I can handle it fine @Criticalz.
@JawsGamezHD, your rank has been set manually.
