### ISSUE TITLE
Entity tags cleared from spawn eggs upon server restart

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#221]
### Expected behavior
Entity tags should stay on spawn eggs

### Actual behavior
Whenever you restart the server the entity tags are removed

### Detailed steps to reproduce this behavior
Give yourself a spawn egg with an entity tag [mcstacker.bimbimma.com] and restart the server. It should now be gone

### Server name
BaseBuilder

### Link to server logs (/dl log)
Unable to upload file

**Comment by MatrixTunnel** [comment]
What plugins do you have installed and are the users op when the tags get removed?

**Comment by iGalaxyYT** [comment]
Essentials, zPermissions, AutoMessenger, I was opped when I tested it, but nobody else online was

**Comment by iGalaxyYT** [comment]
Also Holo Displays and worldedit :P

**Comment by iGalaxyYT** [comment]
Closing issue as my server got griefed, so we're no longer using spawn eggs so we don't need this
