### ISSUE TITLE
Commands.yml is not uploading

### ISSUE THREAD

**Issue by pixelJavascript** [Minehut/Issues#225]
### Expected behavior
When you change the commands.yml in the /mh menu it prompts you to supply a link to your command.yml code on pastebin when entered it will upload it.

### Actual behavior
When you change the commands.yml in the /mh menu it prompts you to supply a link to your command.yml code on pastebin when entered it doesn't do shit.

### Detailed steps to reproduce this behavior
Go into /mh and click on the commands.yml book then supply it a raw pastebin link.

### Server name
Anthem

**Comment by tjhubz** [comment]
#223
