### ISSUE TITLE
[WEB] Add Stripe to Shop

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#232]
**Why?**
Players that don't use PayPal should use stripe. Although most of us could use PayPal and it is not really necessary to get stripe, PayPal doesn't support **all** countries like St. Lucia, Pakistan, etc.. To me, I like to use Stripe since most of the time I use PayPal, it gives me a message saying "Can't complete purchase" or something so, and yes I have confirmed my card.

**Comment by WilliamIsnt** [comment]
You might have gone bankrupt

**Comment by Criticalz** [comment]
True but still, add stripe xd

**Comment by Criticalz** [comment]
Thanks for adding! **CLOSED**
