### ISSUE TITLE
Please Update And Add These Plugins

### ISSUE THREAD

**Issue by FrostedWeFall** [Minehut/Issues#233]
### Expected behavior
N/A

### Actual behavior
N/A

https://www.spigotmc.org/resources/skrayfall.10012/
Allows user to edit NPC Paths, Scoreboards and Tablists!
---------------------------------------------------------------
https://www.spigotmc.org/resources/skript-java-addon-skellett-the-addon-with-a-beast-name.34361/
Pretty much has Everything you will ever need for Skript and Spigot
---------------------------------------------------------------
_https://www.spigotmc.org/resources/addon-umbaska.7352/_
---------------------------------------------------------------

I hope these get updated and added

**Comment by Criticalz** [comment]
Make a Plugin suggestion here: https://github.com/minehut/plugincollection

**Comment by tjhubz** [comment]
As said by criticalz, this is not the place.

**Comment by tjhubz** [comment]
Wrong button oops

**Comment by Trophonix** [comment]
When I added the Skript addons, I looked through the whole list and added any that didn't have any potentially dangerous things. Unfortunately, this means that any we don't currently have, we probably won't ever. I'll do the update, though.
