### ISSUE TITLE
Servers listed with /find should be clickable (feature request)

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#234]
### Expected behavior
When you do /find, (if the player is online) it will display the server that the player is online. The feature I am requesting is for that displayed server to be clickable and send you to that server.

### Actual behavior
/find just displays the nonclickable server name

### Detailed steps to reproduce this behavior
n/a

### Server name
DisasterSurvival

### Link to server logs (/dl log)
n/a

**Comment by lukechatton** [comment]
I like this idea. Let's get it added.

**Comment by MatrixTunnel** [comment]
Added :)
