### ISSUE TITLE
Server stuck at loading plugins

### ISSUE THREAD

**Issue by Scribea** [Minehut/Issues#236]
### Expected behavior
Doing /join Mines and actually getting into the server.

### Actual behavior
Doing /join Mines and stuck at Loading plugins.

### Detailed steps to reproduce this behavior
Before I did /stop and /join, I changed the default world to 'void' from 'world' and now I'm stuck with Loading plugins. Don't you dare say that I have to reset my server, just change bukkit.yml default world back to world.

### Server name
Mines

### Link to server logs (/dl log)
--
---------------
https://gyazo.com/40455706623fb5d5028b41069d1c11c9

**Comment by Scribea** [comment]
Bump

**Comment by Scribea** [comment]
Still needing help on this...

**Comment by tjhubz** [comment]
minehut.com/support

Do not bump posts in the future.

**Comment by Scribea** [comment]
You didnt even try to fix it, just close the issue and basically say "reset your server". Thats nice, you are a very thoughtful person @tjhubz

**Comment by Scribea** [comment]
This would be the 4th time happening and last time Luke said "this shouldn't happen again", well it happened again.

**Comment by tjhubz** [comment]
If I knew how to fix this issue I would help. My server has reset a total of 16 times, y'know. Many of the times it was this issue.

**Comment by Scribea** [comment]
You could change the default world back to 'world' and try that.

**Comment by tjhubz** [comment]
No, I can't. The way everything is setup doesnt allow us to just access everyone's server files. There is a reason we have the reset all direction on the server page.

**Comment by Scribea** [comment]
Mm... but why can Lucas do that then...

**Comment by tjhubz** [comment]
While it may be true that admins are able to fix it, if every single player with this issue bothered them to fix it they would never be able to fix it again. We have to treat all players equally, which, like I said, is why we have reset all on the support page. Please do not be snarky, and please don't bother Lucas multiple times.

**Comment by Jamehh** [comment]
Scribea is annoyed because he owned a really popular server which got rolledback TONNES and got reset loads, and it seems like the staff of minehut don't care.

**Comment by tjhubz** [comment]
It's not that we don't care, it's just that we literally cannot do anything. There are only 3 people who can manually fix this stuff, and they all have actual lives and oyher things to do. Also, in this case it appears the map used was outdated, which caused the issue. It was not our fault.
