### ISSUE TITLE
Lobby "teleport after fall" broken

### ISSUE THREAD

**Issue by JamesPondMC** [Minehut/Issues#24]
Players are being teleported below the spawn after they fall off the map, resulting in them falling into the void again. This creates and endless loop of people getting teleported below the spawn.

Edit:
It's only occurring in lobby 1 and players are initially spawning below the map, not just when they walk off.

**Comment by MatrixTunnel** [comment]
If my guess is right, this could have been caused when Luuke added the "lobby.setspawn" permission to mods somehow resetting the current spawn. 

I just checked now and it seems to be fixed
