### ISSUE TITLE
I just need someone to disable command blocks quickly, please and thank you. (FIXED PLEASE IGNORE)

### ISSUE THREAD

**Issue by Nuttery** [Minehut/Issues#240]
### Expected behavior
Gives me a firework

### Actual behavior
kicks everyone on my server repeatedly.

### Detailed steps to reproduce this behavior
Put down an **always active impulse** command block and input "/give @p minecraft:fireworks 1 0 {Fireworks:{Flight:3,Explosions:[{Type:1,Flicker:0,Trail:1,Colors:[11743532],FadeColors:[3887386]}]}}" in it

### Server name
Contenders

### Link to server logs (/dl log)
Unobtainable.

**Comment by HaZePug** [comment]
Your gonna have to reset your server as admins do not deal with player servers

**Comment by Nuttery** [comment]
Trent told me to write this, I am not resetting.

**Comment by HaZePug** [comment]
There's no other way

**Comment by HaZePug** [comment]
And I know why it kicks you from the game it's because idk why but I tried doing a firework command and it broke my server also
**They is no other way** even if command blocks are disabled they still get kicked, even deleting the command block it woudent work

**Comment by Nuttery** [comment]
requesting lock
