### ISSUE TITLE
Server not starting for a month or so.

### ISSUE THREAD

**Issue by FluffyLeTryhard** [Minehut/Issues#241]
My server has not been starting ever since the recode. The name is DoesntStart, and whenever I try to start it, it says "The server was unresponsive on startup, please try again."

It can only be reproduced on a server that doesn't work, such as mine, and all you do is /join (servername). So, /join DoesntStart to reproduce it.

There is really nothing to add, just I would like to be able to start a server again soon.

Thanks, 

iChinchillinq (Known as FluffyLeTryhard)

**Comment by Scribea** [comment]
Your server is probbably Docker broken and it might need to be reset. Issue #120

**Comment by FluffyLeTryhard** [comment]
I have reset-all and reset-world multiple times, no luck.

**Comment by Trophonix** [comment]
Fixed. The server was docker broken.
