### ISSUE TITLE
Defaulting an uploaded world

### ISSUE THREAD

**Issue by Scribea** [Minehut/Issues#243]
### Expected behavior
When changing the default world to an uploaded world in server.properties it would actually change it.

### Actual behavior
When restarting it's stuck at Loading plugins.

### Detailed steps to reproduce this behavior
Don't know what to write here

### Server name
Mines

### Link to server logs (/dl log)
--

**Comment by Trophonix** [comment]
Resolved. The issue was with the playerdata folder in the world.
