### ISSUE TITLE
[Bug] msg & find session error

### ISSUE THREAD

**Issue by Disastur** [Minehut/Issues#247]
### Expected behavior
Players should be able to /msg and /find other players from any server to any server on the Minehut network
### Actual behavior
It will notify the user "player is offline" or "invalid session" when messaging a player on the server teamgg. when a player uses /find, nothing will be returned to them.
### Detailed steps to reproduce this behavior
go into /server teamgg and type /msg [name] test & /find [name].

### Server name
teamgg

### Link to server logs (/dl log)
- (no access/unavailable)

**Comment by tjhubz** [comment]
This needs to be posted in teamgg issues
