### ISSUE TITLE
No way to cancel old stripe subscription

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#249]
### Expected behavior
There should be some way to cancel an old stripe subscription

### Actual behavior
Can't cancel my tier 2 subscription, so I'm worried it might charge me again.

### Detailed steps to reproduce this behavior
Well... I don't know.

### Server name
KingdomsX

### Link to server logs (/dl log)
https://hastebin.com/uzevacijez (but not needed)

**Comment by Scribea** [comment]
> You will be able to cancel your users' subscription through the Stripe Dashboard page at any time. However, I have not found information about user initiated subscription cancellation requests, so I would like to suggest contacting Stripe Support to find out more information on this.

So you cannot cancel your subscription on your own, you have to ask the seller (Luke) to cancel it. 
Correct me if I am wrong.

**Comment by iGalaxyYT** [comment]
Yeah, I put this up so Luuke would see it.

**Comment by tjhubz** [comment]
Stripe subscriptions were not actually subscriptions, they had to be re-paid for every month. You will not be charged again.
