### ISSUE TITLE
Add Wild-TP (Random TP)

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#255]
**Why?**

Because servers, like Factions, Survival, etc... needs something like this without the player having to walk or tp in a certain area where the land is already claimed. More info is at: https://www.spigotmc.org/resources/wilderness-tp.18431/

**Comment by iGalaxyYT** [comment]
Just use commands.yml with a command that spreads the player around a certain x and z, its free and easy (can also be done with skript but skript requires gold plan)
