### ISSUE TITLE
Update MCRealisticPlus

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#263]
### Expected behavior
MCRealisticPlus works fine with 1.12.1 (1.12) with minor bugs.

### Actual behavior
MCRealisticPlus doesn't work with 1.12 and needs to be updated to a higher version. Find the plugin page (Spigot) here: https://www.spigotmc.org/resources/mcrealisticplus-1-12-support-1-4k-downloads.21628

### Detailed steps to reproduce this behavior
Download and import the newest version of MCRealisticPlus at the page that i stated above.

### Server name
Realistic

### Link to server logs (/dl log)
https://hastebin.com/jaciqawada

**Comment by MatrixTunnel** [comment]
Updated :)
