### ISSUE TITLE
My server is not starting up (Does not even start to load)

### ISSUE THREAD

**Issue by Scribea** [Minehut/Issues#264]
### Expected behavior
When doing /join Mines, it loads the server up and sends you to it.

### Actual behavior
When doing /join Mines it give you this message: https://gyazo.com/2c5e0eb5c40342972e671a6c1723f387 And when doing /shutdown it gives you this message: https://gyazo.com/37defdc63d7b4b339057bfefc6f54ce3

### Detailed steps to reproduce this behavior
Going to lobby, doing /join Mines

### Server name
Mines

### Link to server logs (/dl log)
--

**Comment by tjhubz** [comment]
Your server was started today so I will assume the problem is fixed.
