### ISSUE TITLE
[URGENT] Vote filter not working.

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#269]
### Expected behavior
People shouldn't be able to use words like f*ck and s*x when voting.

### Actual behavior
People are spamming inappropriate votes right now and everyone in the lobby can see them send help.

### Detailed steps to reproduce this behavior
Uhhh... stand in the lobby and watch the chat

### Server name
KingdomsX

### Link to server logs (/dl log)
n/a

**Comment by jorgeberrex** [comment]
This could be easily fixed by checking if the player exists in the database before broadcasting the vote, or just removing the vote broadcasts altogether.

**Comment by tjhubz** [comment]
It's not that it isn't working, it's that it doesn't exist. See #195
