### ISSUE TITLE
Update Ultra Cosmetics

### ISSUE THREAD

**Issue by Criticalz** [Minehut/Issues#273]
**Why?**
More features added; Bug fixes, link:

https://www.spigotmc.org/resources/ultra-cosmetics-opensource-and-free-1-8-1-12.10905/

**Comment by MatrixTunnel** [comment]
The plugin that's available in the menu is currently the latest version. Are you having problems?

**Comment by Criticalz** [comment]
Yes, I am. It keeps saying "New update available" or something similar. Also, I am also having issues with my server itself. I did /setidletimeout 50000 and I keep getting kicked everytime I join it!
