### ISSUE TITLE
Negative Credits

### ISSUE THREAD

**Issue by JackJack33** [Minehut/Issues#295]
### Expected behavior
Credits would stop at 0

### Actual behavior
Player count continues to tax the credits even when they are negative and not able to start server.

### Detailed steps to reproduce this behavior
Let your player count consume the credits, it should go below 0. (I've also heard there was a fix to this not happening for other players)

### Server name
Voidblock

### Link to server logs (/dl log)
Not available due to server not being able to start.

**Comment by Trophonix** [comment]
This problem was fixed. :+1:
