### ISSUE TITLE
Banned players unable to post ban appeals

### ISSUE THREAD

**Issue by JamesPondMC** [Minehut/Issues#3]
When a player is banned the are unable to create a ban appeal on the forums. The [appeals section](https://minehut.com/forums/57b8e87a22f77d3e01bd1a0d) on the forums is currently the only way to appeal a ban, players cannot appeal their ban.

**Comment by lukechatton** [comment]
Leaving this as-is for now until a different appeal process is developed. Forum bans are only issued in severe cases as well, where appeals are essentially worthless.
