### ISSUE TITLE
Lobby Simplification

### ISSUE THREAD

**Issue by lukechatton** [Minehut/Issues#36]
The lobby plugin is currently pretty lackluster. We should find some ways to make it easier for new players to figure things out. 

Possible ideas:
1. Special message sent on login for new players only that describes basic network functionality.
2. Bossbar "news ticker" that has helpful messages for a few seconds at a time. Ex: "Use /create to generate your server", "Purchase upgrades at store.minehut.com", etc.
3. Scoreboard sidebar that shows global player count and amount of servers online. 
4. Re-implement nametag rank prefixes.
5. Show users' server name under their nametag.

**Comment by Trophonix** [comment]
#1 has been added (a message which says "click here to create your free server!")

**Comment by Trophonix** [comment]
Bossbar done

**Comment by Disastur** [comment]
You could use the new advancements?

**Comment by lukechatton** [comment]
We should display the "click here to create your free server!" whenever the player's server profile is null instead of just on first join actually.

**Comment by lukechatton** [comment]
@Disastur I don't think spigot has an API for advancements yet. Once they do we will start to make use of the feature.

**Comment by Trophonix** [comment]
Ohh yeah good point @lukechatton

**Comment by tjhubz** [comment]
Is there a way to show their server under their name without taking up too much space?
Also, disable collision.
