### ISSUE TITLE
Just a small list here...

### ISSUE THREAD

**Issue by PVTvelociraptor** [Minehut/Issues#38]
/find - Tells how long a player has been offline for
/friend - Please re-enable! This was an extremely useful feature. 
Staff Training - I feel like the staff team should recruit some players who are able to stay on at different times than others, as it has become rare to see a staff member moderating the lobby. When this occuros, people beging to spam, advertise, etc.
Valor & Havoc - Valor & Havoc were my two favorite Minehut playlists. I feel like they should be reintroduced to the server with maps made by the community rather than downloaded ones.
Build team - I also honestly believe that a proper build team could be brought together to roll out lobbies & maps for the gamemodes above.
Weekly Featured Servers - I think a cool way to bring players onto more well-developed servers is to hold weekly events on said servers, which brings me to...
Featured servers! - Please make these return, I have heard peeps complaining everywhere for this.
Thank you!

**Comment by Trophonix** [comment]
It would be helpful if you could make individual features/bugs their own issue so discussion can take place on that single issue.
