### ISSUE TITLE
Server ProtocalLib error

### ISSUE THREAD

**Issue by iKarTehFox** [Minehut/Issues#41]
When I started up my server on 1.12, it started to tell me that 'It is unable to inject incoming channel'. Here's a picture.

![error](https://user-images.githubusercontent.com/17345571/26957331-ec6063cc-4c89-11e7-8e84-e22e10b94c9e.PNG)

**Comment by MatrixTunnel** [comment]
I updated ProtocolLib which I think was the cause. If the error continues, send another message here

**Comment by karaoke60000** [comment]
It's still saying it.

**Comment by lukechatton** [comment]
I just rolled out a spigot update. Could you restart your server and test again? @karaoke60000

**Comment by MatrixTunnel** [comment]
It's a bug with ProtocolLib. I checked their GitHub and other people are having the same problem

**Comment by MatrixTunnel** [comment]
They released an update for it and it should be fixed. Let us know if it still does it :)

**Comment by karaoke60000** [comment]
Sorry for not responding to your message. It still says it.

**Comment by MatrixTunnel** [comment]
It's ok! Try restarting your server 3 times and report back if it works then or not :)

**Comment by karaoke60000** [comment]
I just joined my server, it started to flood my chat with errors, then the closed the server down by itself...

**Comment by karaoke60000** [comment]
The server doesn't close down anymore, just so you know.

**Comment by lukechatton** [comment]
Just to confirm, you are saying the issue is resolved now?

**Comment by karaoke60000** [comment]
No

**Comment by Trophonix** [comment]
@karaoke60000 This issue should now be fixed.

**Comment by karaoke60000** [comment]
For me, it seems to still pop up... I'm stumped...

**Comment by MatrixTunnel** [comment]
@karaoke60000 What plugins are you running on your server? I think it might be one of the plugins that uses ProtocolLib

**Comment by karaoke60000** [comment]
Does NCP use ProtocoLib?

**Comment by MatrixTunnel** [comment]
Yes. That hasn't been updated yet so that might be part of the problem

**Comment by iKarTehFox** [comment]
@MatrixTunnel I don't have NCP, I noticed that. Which of my plugins are erroring?

**Comment by MatrixTunnel** [comment]
Since nothing has been reported in the past week, I'm going to consider this resolved
