### ISSUE TITLE
Shopkeepers Plugin

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#44]
After Minehut updated to 1.12, villagers made with the plugin shopkeepers are beable to move and not showing their trades

![98d741257d7119a77b7f3835d64acd03](https://user-images.githubusercontent.com/17933798/26969919-b1da43d4-4d07-11e7-9c59-6866cceea942.png)

**Comment by MatrixTunnel** [comment]
The plugin authors have to update their plugin. I will get to it as soon as possible

(closing since this was reported in a different issue already)
