### ISSUE TITLE
Minecraft World Download/Upload

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#46]
When downloading a world in Minehut using /mchost, it downloads all your world files, but when uploading your world it does NOT upload your scoreboard data. This can cause lots of stuff broken in player server worlds.

Scoreboards data is located in:
world/data/scoreboard.dat

**Comment by MatrixTunnel** [comment]
@sibunanick What world did you try to upload? RedDemptr tried uploading a realms map and it copied the data fine

**Comment by sibunanick** [comment]
My downloaded PVPCrafter world, it imports everything else behave data folder.

**Comment by MatrixTunnel** [comment]
Have you still had any issues with this lately? @sibunanick

**Comment by Trophonix** [comment]
I don't know why it wouldn't upload everything. When you upload a world, it searches the zip for the level.dat and copies *everything* from the folder containing the level.dat into the world folder, which should include the data folder.

**Comment by NickBishop12** [comment]
heres this issue i have i download this world Link:-> https://www.planetminecraft.com/project/farm-ville---survivale-map/ but once downloaded it only download paper NO File can you help me if you can :)
