### ISSUE TITLE
Some of the Plugins not working.

### ISSUE THREAD

**Issue by Mikulasz12** [Minehut/Issues#47]
Hello, I've had some troubles with the plugins, could you update them? (This is a list of  the **plugins** which don't work in 1.12.)

**List:**
_Citizens 
Holographic displays
TitleWelcomeMessage_

**Fixed:**
_Shopkeepers (Not yet, Shopkeepers work, but are a bit buggy)_

**Comment by MatrixTunnel** [comment]
I updated Holographic Displays and Shopkeepers yesterday but after looking into why they were not working, it looks like they don't have support for 1.12 yet. I will be keeping an eye on them and update them as soon as possible

**Comment by Mikulasz12** [comment]
Thanks @MatrixTunnel

**Comment by RedDemptr** [comment]
Shopkeepers seem to work fine for me... https://gfycat.com/GentleInsignificantCreature

**Comment by Mikulasz12** [comment]
Oh, well, on my server it doesn't work, I'm gonna try to reinstall shopkeepers, thanks @RedDemptr

**Comment by MatrixTunnel** [comment]
Citizens has been updated to support 1.12 @Mikulasz12
