### ISSUE TITLE
Not able to install plugins that take up no slots

### ISSUE THREAD

**Issue by XxTurtleDerpxX** [Minehut/Issues#56]
As the title suggests, I am unable to install any plugins that take up no plugin slots. I have 6/6 plugins installed, with some of the no slot plugins installed too, bringing my server plugin count to 17, because of all the essentials things not counting as a plugin etc. and also having the 2 initial BukkitCore and PlayerServer plugins.
    I uninstalled WorldGuard because none of the commands worked, and am now trying to install it again, but I cannot install it because it says "You have reached your maximum plugin limit! Purchase a tier at store.minehut.com to raise this!" even though it takes up no slots. (It says so in the plugin description).

**Comment by lukechatton** [comment]
Working on a fix for this now. Should have something deployed within an hour.

**Comment by lukechatton** [comment]
Deployed!
