### ISSUE TITLE
Gamerule Issue

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#58]
Gamerules are currently not working normally.

**Comment by lukechatton** [comment]
Could you elaborate a bit more? Are they broken in player servers? Is there a specific gamerule that is not functioning properly, or is it all of them? The more information we have the better 😄

**Comment by sibunanick** [comment]
Sorry for the lack of information.

Currently my gamerules are not working, everytime someone joins the server it says [Playername: Block Placed], or a different message. This should automaticlly go away with executing the command /gamerule commandBlockOutput false so the messages are hidden.

I've also tried many other gamerules but it just seems they dont work.
