### ISSUE TITLE
BukkitCore not fully working

### ISSUE THREAD

**Issue by jorgeberrex** [Minehut/Issues#64]
BukkitCore throws errors on PlayerLoginEvent and on command `/minehut`.

PlayerLoginEvent
[latest.log](https://gist.github.com/anonymous/03f3d7118c8b68221d5df1161d0ed03f)

On command `/minehut`
[latest.log](https://gist.github.com/anonymous/d91b49dbe971e10b11f666e8bd30ca03)

It's worth noting that BukkitCore does not show any errors on startup.

**Comment by lukechatton** [comment]
Looks like an issue with the plugins.json menu. @Trophonix should be able to solve this.

**Comment by Trophonix** [comment]
Fixed.
