### ISSUE TITLE
Kicking you out of server.

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#67]
Sorry for placing this many issues, I am just finding a bit too much.

Everytime my redstone line ends it kicks me to the lobby and says.

The server you were previously on went down, you have been connected to a fallback server. But my server is perfectly fine and up and running..

**Comment by MatrixTunnel** [comment]
Are you still having this issue? @sibunanick

**Comment by tjhubz** [comment]
I had this issue yeterday, onve randomly when I was in a server. The next time it happens I will get logs

**Comment by MatrixTunnel** [comment]
After looking into this, it appears some users were in vanish by themselves on the server which was causing the server to shutdown. Please make sure you aren't in vanish after joining yours
