### ISSUE TITLE
NBTEditor Plugin not working

### ISSUE THREAD

**Issue by PsshIm2Cool** [Minehut/Issues#69]
The NBTEditor plugin is a great and big plugin but unfortunately after installing it it doesn't work.
Please fix this when possible!

Thanks!
-Pssh

I have used the NBTEditor plugin on my on Private server before and know the commands.

**Comment by MatrixTunnel** [comment]
Yea, I've been updating all the plugins over the past few days so that will be fixed soon :)

**Comment by MatrixTunnel** [comment]
I updated the plugin so it should work with 1.12 now. Sorry for the delay
Please test the plugin and see if you have any further issues @PsshIm2Cool

**Comment by PsshIm2Cool** [comment]
Thanks for the updates I'll check on it as soon as I come back home!

**Comment by Trophonix** [comment]
Is it fixed @PsshIm2Cool?

**Comment by Trophonix** [comment]
If this issue continues to occur, please open a new issue, as it would then be a separate issue from being outdated.

**Comment by PsshIm2Cool** [comment]
Sorry for the late reply! (I couldn't find the link to the repo) but anyways, the plugin is successfully working and I am able to do commands on the server. 

Thanks for fixing this plugin!
