### ISSUE TITLE
Tier 1-3 Plugins don’t recognize that I’m Tier 3

### ISSUE THREAD

**Issue by Czechiia** [Minehut/Issues#71]
**Note**

- I have shared this issue with Gamer on Discord yesterday, however he did not reply, I noticed the Issue Tracker recently, so I want to apologize in-case what I did was wrong. (The old Discord comment was removed)

**The Issue**
The title says it all. I cannot access any Tier plugins even though I’m Tier 3. I am not sure if this is a server glitch with Minehut 3.0 or if it’s because my Tier is lifetime. However, if it worth noting that I still have 45 Player Slots as-well as 19 Plugin Spaces. 

**Evidence**

There are a few screenshots, so to avoid making this post huge, here's an imgur link of the evidence.

http://imgur.com/a/ndKMC

Thanks for Reading, feel free to contact me on Discord if you see fit.

_Czechia#2389_

**Comment by lukechatton** [comment]
Are you still having issues with this @Czechiia? If I can remember correctly, a patch was pushed out not too long ago that should have fixed this.

**Comment by Czechiia** [comment]
@lukechatton After a brief check, it is still not working. http://imgur.com/a/azSjE

Thanks for Replying

-Czechia

**Comment by MatrixTunnel** [comment]
Main issue: #122
