### ISSUE TITLE
/create formatting

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#73]
When creating a server, if you already have a server it uses white text. This does not stand out and should be changed to aqua/dark aqua.

[![https://gyazo.com/9287c271dbc8912d03bdc565408df6b7](https://gyazo.com/9287c271dbc8912d03bdc565408df6b7/raw)](https://gyazo.com/9287c271dbc8912d03bdc565408df6b7)

**Comment by Trophonix** [comment]
Fixed. Thanks!
