### ISSUE TITLE
Joining different server than requested

### ISSUE THREAD

**Issue by tjhubz** [Minehut/Issues#78]
When joining your server, you will sometimes be sent to a different server.

After resetting my world and setting it to flat (I also updated commands.yml) it sent me to a different server on start.

**Comment by lukechatton** [comment]
What is the name of the server you were trying to join?

**Comment by tjhubz** [comment]
The problem fixed itself after a couple restarts, but the server was SuperSpleef. It has also happened to reddemptr's server.

**Comment by tjhubz** [comment]
Server it sent you to used to be ObjectsPvP, but I think the name changed.

**Comment by tjhubz** [comment]
Server owner is Ninja_Narwhal55, server name YouHub (currently)

**Comment by tjhubz** [comment]
When trying to join YouHub it does not work, but on the forums it appears and in /find
