### ISSUE TITLE
Disconnected from Server

### ISSUE THREAD

**Issue by TheEpicMapMaker** [Minehut/Issues#79]
So I was playing on my server (on Minehut) and suddenly I got kicked off Minehut with a message that said "Connection Lost: Disconnected". I have no idea what is going on so if anyone could help it would be AWESOME! 

PS. /reset-all IS NOT AN OPTION!!

Thanks, TheEpicMapMaker

PPS. Sometimes it just plain crashes, but it doesn't kick me off Minehut.

**Comment by MatrixTunnel** [comment]
Dupe of #67
