### ISSUE TITLE
/save-all not working properly on some servers

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#80]
On some servers, such as mine, /save-all does not have the "please wait for the green success message" thing. It only has Saving... and World saved. It makes it appear that the server is saved, when it actually is not. Please fix this, it has been bugging me for hours. _And yes, I do have sendCommandFeedback set to true._

**Comment by MatrixTunnel** [comment]
We recently redid our storage server setup. If the issue continues, please create a new issue
