### ISSUE TITLE
Holographic Displays plugin uninstalling itself

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#81]
When I install the Holographic Displays plugin and set up the holograms, they appear. But when I /reload the server or /restart the server, the plugin uninstalls. Some of the holograms stay after one /reload, but after a second one they are all gone. This is very annoying, please fix it. Also, I don't know, but this might be the case for all other plugins that appear red when you do /plugins.

**Comment by MatrixTunnel** [comment]
That plugin has been disabled until the plugin authors can update it for 1.12 so that's why it's disappearing

**Comment by Trophonix** [comment]
I modified the plugin menu to not list disabled plugins.
