### ISSUE TITLE
Socialspy can be used to see global Minehut /msg

### ISSUE THREAD

**Issue by HazryG** [Minehut/Issues#84]
Was in a server with Kagaroo and we were /msg-ing each other; owner of the server could see everything that we said through socialspy and was asking questions on his server.

**Comment by lukechatton** [comment]
So it looks like we have a few options here.

1. Disable social spy along with a few other commands (such as /sudo from #75) from Essentials config. We would also have to remove a few plugins, such as the create your own menus plugin. 

2. Move /msg and related commands to the proxy layer. As previously discussed internally, this should be avoided at all costs. 

I'l let @Trophonix way in on the subject before we make any decisions.

**Comment by Draem** [comment]
Can't you disable commands that social spy pickups on in the config?

For /sudo, would be best to just disable it.

**Comment by lukechatton** [comment]
I forgot that we also offer a yml config editor, meaning they could just re-enable it... 

It may be best to just move /msg back to the proxy level.

**Comment by drtshock** [comment]
We can just fork and make that list immutable.

**Comment by drtshock** [comment]
We can just fork and make that list immutable.

**Comment by Draem** [comment]
> As previously discussed internally, this should be avoided at all costs.

You could edit the code for config editor to disable the editing of that section?

**Comment by Draem** [comment]
@drtshock fork what? List of what?

**Comment by Aerh** [comment]
You can also use `/msg` in `/sudo` commands which sends them a message using the Minehut system. This is how some people have been getting banned recently due to others doing that.

**Comment by Aerh** [comment]
You can also use /msg in /sudo commands which sends them a message using the Minehut system. This is how some people have been getting banned recently due to others doing that.

**Comment by MatrixTunnel** [comment]
Fixed.
