### ISSUE TITLE
Paintings disappear but still are there

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#85]
When you attempt to place a painting, it appears for a moment, but then disappears. Even when I place it correctly (1.12 paintings fit the largest space) they still disappear. They still are there, as when I break the block behind them they pop off. I try /reload-ing and it doesn't fix it. I try restarting the server and it doesn't fix it. I try relogging and it doesn't fix it. I don't know if this is a Minecraft bug, but if it is a Minehut bug, please fix it.

**Comment by MatrixTunnel** [comment]
What plugins do you have installed? I can't reproduce this

**Comment by iGalaxyYT** [comment]
Shopkeepers, vault, all essentials, w/g, w/e, create your own menus, item fixer. I believe those are all, but I don't know. Having troubles starting my server at the moment but it should be working fine in a bit.

**Comment by Trophonix** [comment]
The problem might be Item Fixer.

**Comment by iGalaxyYT** [comment]
Item Fixer is for Create Your Own Menus, it blacklists some commands on it. It has nothing to do with physical blocks/items.

**Comment by Trophonix** [comment]
I know what Item Fixer is for, but it modifies NBT data.

**Comment by MatrixTunnel** [comment]
I updated ItemFixer so please reply if the issue has been resolved or not
