### ISSUE TITLE
Many plugins wont work. ex. chat control world edit name tage edit title welcome message. reset-all nothing. reinstalled several times. nothing

### ISSUE THREAD

**Issue by CasualFry** [Minehut/Issues#86]
ex. chat control world edit name tage edit title welcome message. reset-all nothing. reinstalled several times. nothing. Been like this since recode

**Comment by iGalaxyYT** [comment]
Staff are working to fix some plugins, but most need to be updated by the plugin devs themselves.

**Comment by MatrixTunnel** [comment]
NametagEdit and TitleWelcomeMessage were disabled because they haven't been updated to 1.12 yet

**Comment by tjhubz** [comment]
Remember to stop the server before doing /reset-all, it works for me.

**Comment by Trophonix** [comment]
Is this issue still occurring @CasualFry

**Comment by MatrixTunnel** [comment]
NametagEdit and TitleWelcomeMessage haven't been updated to 1.12 and the other plugins are working correctly
