### ISSUE TITLE
Saving issue with session.lock

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#88]
I'm having issues saving my world, I have provided a screenshot in this issue for more information.
![a2195b5f6f95db92ca275c3e4864ffbd](https://user-images.githubusercontent.com/17933798/27084509-75d8c548-504c-11e7-836a-1f0c5c19a104.png)

**Comment by Disastur** [comment]
If you stop your server and reopen it problem should be gone for a long while/forever.  still worth fixing though \o/

**Comment by MatrixTunnel** [comment]
Does this still happen?
