### ISSUE TITLE
Shows update messages when opped

### ISSUE THREAD

**Issue by sibunanick** [Minehut/Issues#89]
When a player is opped on a server and a lot of commandblocks are involved you will receive messages like [scoreboard]: Block Placed or executing messages like title command succesfully executed.

This does also show when /gamerule CommandBlockOutput is false and true.

It only shows when players are opped, but you can get spammed easly.

![aca657e66fb19dc358ae1abe0310d029](https://user-images.githubusercontent.com/17933798/27084782-6ade47e8-504d-11e7-91d9-c98434ac71eb.png)

**Comment by RedDemptr** [comment]
I think this happens if you're using a plugin to run some of the commands but if you do `/gamerule sendCommandFeedback false` it stops it

**Comment by sibunanick** [comment]
I am not using any plugins to perform that, I'll try later if this will fix it.

**Comment by MatrixTunnel** [comment]
Since this is probably a gamerule issue and nothing has been posted here for about a week, I am going to close it. If this issue persists, please triple check everything before commenting on this issue again :)
