### ISSUE TITLE
/hub is picked up by the repeated command filter

### ISSUE THREAD

**Issue by iGalaxyYT** [Minehut/Issues#90]
When I try to do /hub a couple times it says to not repeat the same command. I am not on my own server, so I don't know what plugins are installed. I was able to do /lobby, but that should probably get fixed...

**Comment by Trophonix** [comment]
That would be the plugin ChatControl.

**Comment by iGalaxyYT** [comment]
Well then that's just the same plugin problem everyone is reporting, sorry for reporting it :P
