### ISSUE TITLE
My Server Will Not Start.

### ISSUE THREAD

**Issue by HoneydewHolt** [Minehut/Issues#91]
When I run the /join DanqClicker, it saids everything like normal but it keeps saying "Starting Up Server".
It keeps repeating and does not stop! plz fix or help!

**Comment by iGalaxyYT** [comment]
Don't report things like this, just wait a while and it will work. (I'm not staff but I'm sure they will say the same)

**Comment by lukechatton** [comment]
This is due to our storage server being overloaded. We are actively working on a fix. I'l have a new issue posted soon that will include progress on the new setup.
