### ISSUE TITLE
halppppp

### ISSUE THREAD

**Issue by Rei301** [Minehut/Issues#92]
Hey its me Rei301, and im having an issue with essentials group manager, not being able to add perms, or putting people into certain groups. it states "an internal error occured while attempting to preform this command" i will list the plugins i have right here:

*All the essentials plugins,
*World edit
*Vault
*Protocol Lib
*Shopkeepers
*Create Your own Menu's
and thats all of the plugins i have.

Please help, as this is causing a major issue for me.

-Rei301

**Comment by Trophonix** [comment]
Another issue has been posted for this with a more appropriate name: #94
