### ISSUE TITLE
[Minehut] GroupManager ./manuadd not working!

### ISSUE THREAD

**Issue by waz99OSTB** [Minehut/Issues#94]
Today, me and my friends started up a server, and were planning on a minigames server because I have tier 5, and when adding ranks, it wouldn't let me add Groups. It said we were "null"

**Comment by Trophonix** [comment]
Try using GroupManagerX. It's next to GroupManager in the menu and is supposed to work with later versions, but we've had trouble with it in the past so I added it separately.

**Comment by Trophonix** [comment]
Try using GroupManagerX. It's next to GroupManager in the menu and is supposed to work with later versions, but we've had trouble with it in the past so I added it separately. @waz99OSTB

**Comment by MatrixTunnel** [comment]
Fixed! Reinstall GroupManager to make sure you have the latest working version :)
